#![allow(dead_code)]

use crate::ast::*;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct DocItem {
    pub name: String,
    pub doc_comment: String,
    pub signature: String,
    pub item_type: String, // "function", "struct", "enum", "trait", "module"
}

pub fn extract_doc_comments(source: &str) -> Vec<(String, String)> {
    let mut comments = Vec::new();
    let mut current_doc = Vec::new();

    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("///") {
            current_doc.push(trimmed.trim_start_matches("///").trim().to_string());
        } else if (trimmed.starts_with("fn ") || trimmed.starts_with("struct ") || trimmed.starts_with("enum ") || trimmed.starts_with("trait ")) && !current_doc.is_empty() {
            let name = trimmed.split_whitespace().nth(1).unwrap_or("").split('(').next().unwrap_or("").to_string();
            comments.push((name, current_doc.join("\n")));
            current_doc.clear();
        } else if !trimmed.is_empty() && !trimmed.starts_with("//") {
            current_doc.clear();
        }
    }
    comments
}

pub fn generate_html_docs(program: &Program, source: &str, project_name: &str, output_dir: &Path) -> std::io::Result<()> {
    let doc_map = extract_doc_comments(source);
    let get_doc = |name: &str| -> String {
        for (n, d) in &doc_map {
            if n == name {
                return d.clone();
            }
        }
        "No documentation provided.".to_string()
    };

    let modules_dir = output_dir.join("modules");
    let structs_dir = output_dir.join("structs");
    let functions_dir = output_dir.join("functions");
    let traits_dir = output_dir.join("traits");

    fs::create_dir_all(&modules_dir)?;
    fs::create_dir_all(&structs_dir)?;
    fs::create_dir_all(&functions_dir)?;
    fs::create_dir_all(&traits_dir)?;

    let mut functions = Vec::new();
    let mut structs = Vec::new();
    let mut enums = Vec::new();

    for stmt in &program.statements {
        match &stmt.kind {
            StmtKind::Function { name, is_async, params, ret_type, .. } => {
                let async_badge = if *is_async { "async " } else { "" };
                let p_strs: Vec<String> = params.iter().map(|(p, t)| format!("{}: {:?}", p, t)).collect();
                let sig = format!("{}fn {}({}) -> {:?}", async_badge, name, p_strs.join(", "), ret_type);
                let doc = get_doc(name);
                functions.push((name.clone(), sig, doc));
            }
            StmtKind::StructDecl { name, fields, .. } => {
                let mut sig = format!("struct {} {{\n", name);
                for (f, t) in fields {
                    sig.push_str(&format!("    {}: {:?},\n", f, t));
                }
                sig.push_str("}");
                let doc = get_doc(name);
                structs.push((name.clone(), sig, doc));
            }
            StmtKind::EnumDecl { name, variants, .. } => {
                let mut sig = format!("enum {} {{\n", name);
                for (v, p) in variants {
                    if let Some(payload) = p {
                        sig.push_str(&format!("    {}({:?}),\n", v, payload));
                    } else {
                        sig.push_str(&format!("    {},\n", v));
                    }
                }
                sig.push_str("}");
                let doc = get_doc(name);
                enums.push((name.clone(), sig, doc));
            }
            _ => {}
        }
    }

    // 1. Generate index.html
    let mut index_html = String::new();
    index_html.push_str(&render_html_header(&format!("API Reference - {}", project_name)));
    index_html.push_str(&format!("<h1>🌌 {} Documentation</h1>\n", project_name));
    index_html.push_str("<p class='lead'>Fast, Safe, Elegant & High-Performance Language Reference generated by <code>sorayunara doc</code>.</p>\n<hr/>\n");

    index_html.push_str("<h2>⚡ Functions</h2>\n<ul class='item-list'>\n");
    for (name, sig, doc) in &functions {
        index_html.push_str(&format!("<li><a href='functions/{}.html'><code>{}</code></a> — <span class='summary'>{}</span></li>\n", name, name, doc.lines().next().unwrap_or("")));
        let fn_page = render_item_page(name, "Function", sig, doc, "../index.html");
        fs::write(functions_dir.join(format!("{}.html", name)), fn_page)?;
    }
    index_html.push_str("</ul>\n");

    index_html.push_str("<h2>📦 Structs</h2>\n<ul class='item-list'>\n");
    for (name, sig, doc) in &structs {
        index_html.push_str(&format!("<li><a href='structs/{}.html'><code>{}</code></a> — <span class='summary'>{}</span></li>\n", name, name, doc.lines().next().unwrap_or("")));
        let struct_page = render_item_page(name, "Struct", sig, doc, "../index.html");
        fs::write(structs_dir.join(format!("{}.html", name)), struct_page)?;
    }
    index_html.push_str("</ul>\n");

    index_html.push_str(&render_html_footer());
    fs::write(output_dir.join("index.html"), index_html)?;

    // Create index stubs for modules/ and traits/
    let mod_index = render_section_index("Modules", "Available Sorayunara standard and application modules", &[]);
    fs::write(modules_dir.join("index.html"), mod_index)?;

    let traits_index = render_section_index("Traits & Interfaces", "Sorayunara type traits and interface contracts", &[]);
    fs::write(traits_dir.join("index.html"), traits_index)?;

    Ok(())
}

fn render_html_header(title: &str) -> String {
    format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{}</title>
    <style>
        :root {{
            --bg: #0d1117;
            --fg: #c9d1d9;
            --accent: #58a6ff;
            --code-bg: #161b22;
            --border: #30363d;
            --card-bg: #161b22;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg);
            color: var(--fg);
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
        }}
        h1, h2, h3 {{ color: #ffffff; }}
        a {{ color: var(--accent); text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        pre, code {{
            font-family: "JetBrains Mono", Consolas, Menlo, monospace;
            background-color: var(--code-bg);
            border-radius: 6px;
        }}
        pre {{
            padding: 16px;
            border: 1px solid var(--border);
            overflow-x: auto;
        }}
        code {{ padding: 2px 6px; }}
        .item-list {{ list-style-type: none; padding-left: 0; }}
        .item-list li {{
            background: var(--card-bg);
            border: 1px solid var(--border);
            margin-bottom: 8px;
            padding: 12px 16px;
            border-radius: 6px;
        }}
        .doc-section {{
            background: var(--card-bg);
            padding: 20px;
            border: 1px solid var(--border);
            border-radius: 8px;
            margin-top: 20px;
            white-space: pre-wrap;
        }}
        .back-link {{ display: inline-block; margin-bottom: 20px; }}
    </style>
</head>
<body>
<div class="container">
"#, title)
}

fn render_html_footer() -> String {
    r#"
</div>
</body>
</html>
"#.to_string()
}

fn render_item_page(name: &str, kind: &str, signature: &str, doc: &str, back_href: &str) -> String {
    let mut s = String::new();
    s.push_str(&render_html_header(&format!("{} {} - Aether Docs", kind, name)));
    s.push_str(&format!("<a class='back-link' href='{}'>← Back to Overview</a>\n", back_href));
    s.push_str(&format!("<h1>{} <code>{}</code></h1>\n", kind, name));
    s.push_str("<h3>Declaration</h3>\n");
    s.push_str(&format!("<pre><code>{}</code></pre>\n", signature));
    s.push_str("<h3>Documentation</h3>\n");
    s.push_str(&format!("<div class='doc-section'>{}</div>\n", doc));
    s.push_str(&render_html_footer());
    s
}

fn render_section_index(title: &str, desc: &str, items: &[String]) -> String {
    let mut s = String::new();
    s.push_str(&render_html_header(title));
    s.push_str("<a class='back-link' href='../index.html'>← Back to Overview</a>\n");
    s.push_str(&format!("<h1>{}</h1>\n<p>{}</p>\n", title, desc));
    s.push_str("<ul class='item-list'>\n");
    if items.is_empty() {
        s.push_str("<li><em>No items registered yet.</em></li>\n");
    } else {
        for it in items {
            s.push_str(&format!("<li>{}</li>\n", it));
        }
    }
    s.push_str("</ul>\n");
    s.push_str(&render_html_footer());
    s
}

pub fn generate_docs(program: &Program, project_name: &str) -> String {
    let mut doc = String::new();
    doc.push_str(&format!("# API Documentation: {}\n\n", project_name));
    doc.push_str("Generated by `aether doc` toolchain.\n\n---\n\n");

    let mut structs = Vec::new();
    let mut enums = Vec::new();
    let mut functions = Vec::new();

    for stmt in &program.statements {
        match &stmt.kind {
            StmtKind::StructDecl { name, fields, .. } => structs.push((name, fields)),
            StmtKind::EnumDecl { name, variants, .. } => enums.push((name, variants)),
            StmtKind::Function {
                name,
                is_async,
                params,
                ret_type,
                ..
            } => functions.push((name, is_async, params, ret_type)),
            _ => {}
        }
    }

    if !functions.is_empty() {
        doc.push_str("## ⚡ Functions\n\n");
        for (name, is_async, params, ret_type) in functions {
            let async_badge = if *is_async { "`async` " } else { "" };
            let p_strs: Vec<String> = params.iter().map(|(p, t)| format!("{}: {:?}", p, t)).collect();
            doc.push_str(&format!("### {}`fn {}({}) -> {:?}`\n\n", async_badge, name, p_strs.join(", "), ret_type));
        }
    }

    if !structs.is_empty() {
        doc.push_str("## 📦 Structs\n\n");
        for (name, fields) in structs {
            doc.push_str(&format!("### `struct {}`\n\n", name));
            doc.push_str("| Field | Type |\n|---|---|\n");
            for (f, t) in fields {
                doc.push_str(&format!("| `{}` | `{:?}` |\n", f, t));
            }
            doc.push_str("\n");
        }
    }

    doc
}
