#![allow(dead_code)]

use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum: String,
    pub dependencies: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct SorayunaraLock {
    pub lock_version: u32,
    pub packages: Vec<LockedPackage>,
}

pub type AoiLock = SorayunaraLock;
pub type NamiLock = SorayunaraLock;
pub type AetherLock = SorayunaraLock;

impl SorayunaraLock {
    pub fn new() -> Self {
        Self {
            lock_version: 1,
            packages: Vec::new(),
        }
    }

    pub fn to_toml(&self) -> String {
        let mut s = String::new();
        s.push_str(
            "# This file is automatically generated by Sorayunara for reproducible builds.\n",
        );
        s.push_str("# Manual editing is not recommended.\n\n");
        s.push_str(&format!("version = {}\n\n", self.lock_version));

        for pkg in &self.packages {
            s.push_str("[[package]]\n");
            s.push_str(&format!("name = \"{}\"\n", pkg.name));
            s.push_str(&format!("version = \"{}\"\n", pkg.version));
            s.push_str(&format!("source = \"{}\"\n", pkg.source));
            s.push_str(&format!("checksum = \"{}\"\n", pkg.checksum));
            if !pkg.dependencies.is_empty() {
                let deps_str = pkg
                    .dependencies
                    .iter()
                    .map(|d| format!("\"{}\"", d))
                    .collect::<Vec<_>>()
                    .join(", ");
                s.push_str(&format!("dependencies = [{}]\n", deps_str));
            } else {
                s.push_str("dependencies = []\n");
            }
            s.push('\n');
        }

        s
    }

    pub fn parse(content: &str) -> Result<Self, String> {
        let mut packages = Vec::new();
        let mut current_name = None;
        let mut current_ver = None;
        let mut current_src = None;
        let mut current_sum = None;
        let mut current_deps = Vec::new();
        let mut in_pkg = false;

        for line in content.lines() {
            let line = line.trim();
            if line.starts_with("#") || line.is_empty() {
                continue;
            }

            if line == "[[package]]" {
                if in_pkg {
                    if let (Some(n), Some(v)) = (current_name.take(), current_ver.take()) {
                        packages.push(LockedPackage {
                            name: n,
                            version: v,
                            source: current_src.take().unwrap_or_default(),
                            checksum: current_sum.take().unwrap_or_default(),
                            dependencies: current_deps.drain(..).collect(),
                        });
                    }
                }
                in_pkg = true;
                continue;
            }

            if in_pkg {
                if let Some((k, v)) = line.split_once('=') {
                    let key = k.trim();
                    let val = v.trim().trim_matches('"');
                    match key {
                        "name" => current_name = Some(val.to_string()),
                        "version" => current_ver = Some(val.to_string()),
                        "source" => current_src = Some(val.to_string()),
                        "checksum" => current_sum = Some(val.to_string()),
                        "dependencies" => {
                            let array_str = v.trim().trim_start_matches('[').trim_end_matches(']');
                            current_deps = array_str
                                .split(',')
                                .map(|s| s.trim().trim_matches('"'))
                                .filter(|s| !s.is_empty())
                                .map(|s| s.to_string())
                                .collect();
                        }
                        _ => {}
                    }
                }
            }
        }

        if in_pkg {
            if let (Some(n), Some(v)) = (current_name, current_ver) {
                packages.push(LockedPackage {
                    name: n,
                    version: v,
                    source: current_src.unwrap_or_default(),
                    checksum: current_sum.unwrap_or_default(),
                    dependencies: current_deps,
                });
            }
        }

        Ok(Self {
            lock_version: 1,
            packages,
        })
    }

    pub fn verify_checksums(
        &self,
        registry_checksums: &HashMap<String, String>,
    ) -> Result<(), String> {
        for pkg in &self.packages {
            if let Some(expected_sum) = registry_checksums.get(&pkg.name) {
                if &pkg.checksum != expected_sum {
                    return Err(format!(
                        "Integrity error: checksum mismatch for package '{}' (locked: {}, expected: {})",
                        pkg.name, pkg.checksum, expected_sum
                    ));
                }
            }
        }
        Ok(())
    }

    pub fn restore_reproducible_build(&self, project_dir: &Path) -> Result<usize, String> {
        let pkg_root = project_dir.join(".sorayunara").join("packages");
        fs::create_dir_all(&pkg_root)
            .map_err(|e| format!("Failed to create packages root: {}", e))?;

        for pkg in &self.packages {
            let pkg_dir = pkg_root.join(&pkg.name).join(&pkg.version);
            fs::create_dir_all(&pkg_dir)
                .map_err(|e| format!("Failed to create package dir: {}", e))?;

            let info_content = format!(
                "// Generated reproducible bundle for {} v{}\n// Checksum: {}\n// Source: {}\n",
                pkg.name, pkg.version, pkg.checksum, pkg.source
            );
            fs::write(pkg_dir.join("pkg.info"), info_content)
                .map_err(|e| format!("Failed to write package info: {}", e))?;
        }

        Ok(self.packages.len())
    }
}
