[package]
name = "sorayunara"
version = "0.1.0"
edition = "2024"
authors = ["Sorayunara <dev@sorayunara.org>"]
description = "Sorayunara (.sora) — Next-Generation Systems & Backend Language with Hindley-Milner Type Inference, Flow-Sensitive Borrow Checking, Actor Concurrency, and Multi-Target LLVM/WASM/C Native Codegen."

[[bin]]
name = "sorayunara"
path = "bootstrap/src/main.rs"

[[bin]]
name = "sora"
path = "bootstrap/src/main.rs"

[lib]
name = "sorayunara"
path = "bootstrap/src/lib.rs"

[dependencies]

