#![allow(dead_code)]

use super::token_kind::TokenKind;

pub fn lookup_keyword(ident: &str) -> Option<TokenKind> {
    match ident {
        "fn" => Some(TokenKind::Fn),
        "let" => Some(TokenKind::Let),
        "mut" => Some(TokenKind::Mut),
        "const" => Some(TokenKind::Const),
        "return" => Some(TokenKind::Return),
        "print" => Some(TokenKind::Print),
        "if" => Some(TokenKind::If),
        "else" => Some(TokenKind::Else),
        "while" => Some(TokenKind::While),
        "for" => Some(TokenKind::For),
        "in" => Some(TokenKind::In),
        "loop" => Some(TokenKind::Loop),
        "break" => Some(TokenKind::Break),
        "continue" => Some(TokenKind::Continue),
        "struct" => Some(TokenKind::Struct),
        "enum" => Some(TokenKind::Enum),
        "type" => Some(TokenKind::Type),
        "trait" => Some(TokenKind::Trait),
        "impl" => Some(TokenKind::Impl),
        "operator" => Some(TokenKind::Operator),
        "match" => Some(TokenKind::Match),
        "is" => Some(TokenKind::Is),
        "import" => Some(TokenKind::Import),
        "mod" => Some(TokenKind::Mod),
        "true" => Some(TokenKind::True),
        "false" => Some(TokenKind::False),
        "null" => Some(TokenKind::Null),
        "Some" => Some(TokenKind::Some),
        "None" => Some(TokenKind::None),
        "Ok" => Some(TokenKind::Ok),
        "Err" => Some(TokenKind::Err),
        "move" => Some(TokenKind::Move),
        "unsafe" => Some(TokenKind::Unsafe),
        "async" => Some(TokenKind::Async),
        "await" => Some(TokenKind::Await),
        "Task" => Some(TokenKind::Task),
        "spawn" => Some(TokenKind::Spawn),
        "Chan" => Some(TokenKind::Chan),
        "scope" => Some(TokenKind::Scope),
        "comptime" => Some(TokenKind::Comptime),
        "extern" => Some(TokenKind::Extern),
        "test" => Some(TokenKind::Test),
        "assert" => Some(TokenKind::Assert),
        _ => None,
    }
}
